name: patch_ir_spike
publish_to: none
environment:
  sdk: ^3.11.0
dependencies:
  crypto: ^3.0.6
  pointycastle: 4.0.0
  dynamic_modules:
    path: ../../work/upstream/dart-sdk/pkg/dynamic_modules
  kernel:
    path: ../../work/upstream/dart-sdk/pkg/kernel
dependency_overrides:
  _fe_analyzer_shared:
    path: ../../work/upstream/dart-sdk/pkg/_fe_analyzer_shared
